Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Lists:
Lists are dynamic data structures in Python.
They can hold elements of different data types.
Lists allow for easy resizing during runtime.
You can perform operations like appending, inserting, or deleting elements.
Lists are more flexible due to their adaptability.
Arrays:
Arrays are fundamental data structures.
They store elements of the same data type in contiguous memory.
Arrays have a fixed size set during creation.
Accessing elements in arrays is faster due to direct indexing.
Arrays are less flexible as their size cannot be easily changed.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object=list_)

print(f"Data type of 'list_': {type(list_)}")
print(f"Data type of 'array_list': {type(array_list)}")


Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [2]:
import numpy as np

# Create a list
list_ = ['1', '2', '3', '4', '5']

# Create an array from the list
array_list = np.array(object=list_)

# Print data types of each element in 'list_'
print("Data types in 'list_':")
for item in list_:
    print(f"Element '{item}' has data type: {type(item)}")

# Print data types of each element in 'array_list'
print("\nData types in 'array_list':")
for item in array_list:
    print(f"Element '{item}' has data type: {type(item)}")


Data types in 'list_':
Element '1' has data type: <class 'str'>
Element '2' has data type: <class 'str'>
Element '3' has data type: <class 'str'>
Element '4' has data type: <class 'str'>
Element '5' has data type: <class 'str'>

Data types in 'array_list':
Element '1' has data type: <class 'numpy.str_'>
Element '2' has data type: <class 'numpy.str_'>
Element '3' has data type: <class 'numpy.str_'>
Element '4' has data type: <class 'numpy.str_'>
Element '5' has data type: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [3]:
import numpy as np

# Create a list
list_ = ['1', '2', '3', '4', '5']

# Create an array from the list
array_list = np.array(object=list_ , dtype = int)

# Print data types of each element in 'list_'
print("Data types in 'list_':")
for item in list_:
    print(f"Element '{item}' has data type: {type(item)}")

# Print data types of each element in 'array_list'
print("\nData types in 'array_list':")
for item in array_list:
    print(f"Element '{item}' has data type: {type(item)}")

Data types in 'list_':
Element '1' has data type: <class 'str'>
Element '2' has data type: <class 'str'>
Element '3' has data type: <class 'str'>
Element '4' has data type: <class 'str'>
Element '5' has data type: <class 'str'>

Data types in 'array_list':
Element '1' has data type: <class 'numpy.int64'>
Element '2' has data type: <class 'numpy.int64'>
Element '3' has data type: <class 'numpy.int64'>
Element '4' has data type: <class 'numpy.int64'>
Element '5' has data type: <class 'numpy.int64'>


import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [4]:
import numpy as np

# Given list
num_list = [[1, 2, 3], [4, 5, 6]]

# Create a NumPy array
num_array = np.array(object=num_list)

# (i) Shape of the array
shape = num_array.shape

# (ii) Size of the array
size = num_array.size

print(f"Shape of num_array: {shape}")
print(f"Size of num_array: {size}")


Shape of num_array: (2, 3)
Size of num_array: 6


The shape (2, 3) indicates that num_array has 2 rows and 3 columns.
The size 6 represents the total number of elements in the array.

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [11]:
import numpy as np

# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

print("3x3 Matrix of Zeros:")
print(zero_matrix)
print(f"array shape : {np.shape(zero_matrix)}")
print(f"array shape : {np.size(zero_matrix)}")

3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
array shape : (3, 3)
array shape : 9


Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [13]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5,5)

print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
